# Generated by Django 2.1.3 on 2020-01-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_post_shop_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shop_field',
        ),
        migrations.AddField(
            model_name='post',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='Quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
