# Generated by Django 2.1.3 on 2020-01-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200106_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='title',
        ),
    ]
