# Generated by Django 2.1.3 on 2020-01-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=1, help_text='150x150px', upload_to='img/%Y/%m/%d', verbose_name='Ссылка картинки'),
            preserve_default=False,
        ),
    ]
